### ISSUE TITLE
When is the debug information loaded?

### ISSUE THREAD

**Issue by dilyanpalauzov** [google/sanitizers#1082]
Does AddressSanitizer load the debug symbols when the program is loaded, or later during the crash, when the debug symbols are necessary?

Please update the table at  https://github.com/google/sanitizers/wiki/AddressSanitizerComparisonOfMemoryTools to state, with information, when is debug information loaded.

**Comment by kcc** [comment]
symbolization typically happens only when a bug is reported, but I don't think we should be providing any guarantees in this space.

**Comment by dilyanpalauzov** [comment]
The question was, when the debug information is loaded.

I think valgrind first loads all the debug information and then starts executing.  So if the RAM is not enouh for all the debug symbols from all libraries, then valgrind cannot be used, or something has to be sacrified (stripping).

This contrasts to Asan, where the debug information is lloaded only when necessary, and not all debug information is loaded then.

This contrast deserves to be documented.

**Comment by kcc** [comment]
asan doesn't do anything like valgrind in this space. 
valgrind pre-loads and pre-processes debug info so that the DWARF's CFI annotations can be used for (relatively) fast stack unwinding. 
ASan by default relies on frame pointers to unwind the stack and so doesn't need CFI annotations.
If you use `ASAN_OPTIONS=fast_unwind_on_malloc=false` (which is not default) then a system unwinder will be used, which is likely to use the CFI directives and thus load the debug info on the first unwind.
