### ISSUE TITLE
Identifying function start guards when using sanitizer coverage

### ISSUE THREAD

**Issue by prashast** [google/sanitizers#1198]
Hi, I wanted to identify guard locations corresponding to function starts when using edge coverage instrumentation (`-fsanitize-coverage=edge,trace-pc-guard`). The reason I do not just use `-fsanitize-coverage=func,trace-pc-guard` is because I do not want _only_ the function starts to be instrumented.

The solution that I have for now is to perform a postprocessing phase and identify the guard location for function starts by analyzing the instrumented binary and seeing the argument passed to `__sanitizer_cov_trace_pc_guard`. Does this seem like a reasonable way or is there a less hackier approach to identifying the function start guards that I might be missing? For eg., is there somewhere in the Clang toolchain itself where I could dump this information (or make changes to dump it) about function start guards rather than performing this postprocessing?

**Comment by kcc** [comment]
We solve exactly this problem in libFuzzer, where we instrument all edges but need special treatment for function entries. Please check https://clang.llvm.org/docs/SanitizerCoverage.html#pc-table

**Comment by prashast** [comment]
Thanks! This does indeed give exactly the information I need.

**Comment by dvyukov** [comment]
On a related note, is it possible to detect function exits so that trace reply would allow to restore stack trace for each coverage point?

**Comment by kcc** [comment]
Not out of the box. 
An easy solution would be to mark blocks that are the last instrumented blocks before the exits, 
the same way we mark entry blocks. But this would be imperfect since the exit blocks themselves are not necessarily instrumented. 
Another solution is to instrument the exit blocks themselves, and also inser the instrumentation at the end of the blocks instead of the beginnings. Clearly doable, just someone needs to do it.
