### ISSUE TITLE
LSan doesn't detect leaks with mmap

### ISSUE THREAD

**Issue by hyukmyeong** [google/sanitizers#1224]
Hello, thank you for this project
While I'm using LSan I found that it doesn't detect leaks with mmap

Is there any reason why ?
It must be great if someone let me know !

test code is simple like below

```cpp
#include <sys/mman.h>

int main() {
    int* ptr2 = (int*)mmap(0, 4096, PROT_READ|PROT_WRITE, MAP_ANONYMOUS|MAP_PRIVATE, -1, 0);
}
```

**Comment by kcc** [comment]
lsan is a heap (malloc) leak detector.
 
It's hard to even define what is an mmap leak, because mmap-ed data doesn't really ever leak - you can still find all the mappings in /proc/maps and unmap what you don't need, even if all pointers to that mapping are lost. 

It should be possible to extend lsan to do the following: 
  * scan all memory to find all pointers to all currently mmap-ed regions (lsan does the full scan anyway). 
  * report mappings that no pointers are pointing to

I don't know how useful such tool is going to be. 
(And we are not planing this work)

**Comment by hyukmyeong** [comment]
Thank you for the comment
I learned much^^
