### ISSUE TITLE
Lock escalation not reported under TSAN

### ISSUE THREAD

**Issue by dawesc** [google/sanitizers#1275]
Although not stictly a threading issue it's definitely not address sanitization we have some bad code where we have a shared_lock on a mutex and then we try to get the unique_lock on it; a really simple example is:

```
#include <shared_mutex>
#include <iostream>

std::shared_timed_mutex m;

int main() {
  // both the threads get access to the integer i
  std::shared_lock<std::shared_timed_mutex> lockShared(m);
  std::cout << "OK!" << std::endl;
  std::unique_lock<std::shared_timed_mutex> lockUnique(m);
  std::cout << "CANNOT GET HERE!" << std::endl;
}
```
Run as:
```
clang++ -fsanitize=thread --std=c++17 test.cpp && ./a.out
```

Of course having the shared_lock we can NEVER get into the unique_lock. It would be increddibly useful if these kind of escalation issues where an upgrade should have been used are reported by TSAN (or some other lock sanitizer?).

**Comment by melver** [comment]
Generally, if you lock up like this, ThreadSanitizer won't tell you much more than e.g. attaching gdb and showing a stack trace for all threads.

If you want a tool that is a bit more verbose about this, you can use a userspace variant of the Linux kernel's lockdep lock validator: https://lwn.net/Articles/536363/ ( It is available prebuilt on e.g. Debian based systems: apt install liblockdep-dev. )

With your program above, you can then see the issue:

$ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/liblockdep.so.4.19 ./a.out
OK!

============================================
WARNING: possible recursive locking detected
liblockdep 4.19 
--------------------------------------------
a.out/1972117 is trying to acquire lock:
0x5636608cdeb8 (0x56365ea461a0){....}, at: 0x56365ea43357S

but task is already holding lock:
0x5636608cdeb8 (0x56365ea461a0){....}, at: 0x56365ea43328S

other info that might help us debug this:
 Possible unsafe locking scenario:

       CPU0
       ----
  lock(0x56365ea461a0);
  lock(0x56365ea461a0);

 *** DEADLOCK ***

 May be due to missing lock nesting notation

1 lock held by a.out/1972117:
 #0: 0x5636608cdeb8 (0x56365ea461a0){....}, at: 0x56365ea43328S

stack backtrace:
/usr/lib/x86_64-linux-gnu/liblockdep.so.4.19(+0x264b)[0x7fb2fa41364b]
/usr/lib/x86_64-linux-gnu/liblockdep.so.4.19(+0x4c0d)[0x7fb2fa415c0d]
/usr/lib/x86_64-linux-gnu/liblockdep.so.4.19(lock_acquire+0x57)[0x7fb2fa416797]
/usr/lib/x86_64-linux-gnu/liblockdep.so.4.19(pthread_rwlock_wrlock+0x33)[0x7fb2fa417bd3]
./a.out(+0x1357)[0x56365ea43357]
./a.out(+0x13a8)[0x56365ea433a8]
./a.out(+0x1446)[0x56365ea43446]
./a.out(+0x15c1)[0x56365ea435c1]
./a.out(+0x1539)[0x56365ea43539]
./a.out(+0x122b)[0x56365ea4322b]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb)[0x7fb2fa046e0b]
./a.out(+0x10fa)[0x56365ea430fa]

**Comment by dawesc** [comment]
Thank you so much @melver that is more useful than i could have ever hoped for and will save me hours of prodding!
