### ISSUE TITLE
Do sanitizers support C++20 Coroutines for GCC?

### ISSUE THREAD

**Issue by swang206** [google/sanitizers#1284]
I use coroutines. The sanitizer complains. I do not know whether it is a bug in my program or it is because sanitizers have not yet supported coroutines.

**Comment by kcc** [comment]
Please reopen with a reproducer. 
Please also check with the latest Clang.

**Comment by expnkx** [comment]
> Please reopen with a reproducer.
> Please also check with the latest Clang.

Well, Clang sucks for C++ 20 support since it does not correctly support Concepts.

**Comment by pfez** [comment]
Hi, same problem here!

I tried to shrink it to a minimal reproducer. It's using clang trunk and you can find it here on godbolt: https://godbolt.org/z/W3cPW6

Leak Sanitizer reports a leak. My guess is that the sanitizer is detecting that the coroutine state is leaking. Not sure if this is caused by clang failing to destroy the coroutine state after `co_return` (like C++20 standard says it should do) or if it's a false positive of Leak Sanitizer (so, clang properly destroys the coroutine state, but the sanitizer fails to see it somehow). Still trying to figure it out looking at the disassembly...

**Comment by pfez** [comment]
Weird, I'm still poking around with that example in godbolt. I get the leak report with optimization levels `-O0`, `-O2`, `-O3`, `-Os` and `-Oz`, but not with `-O1`. Not sure if this is meaningful.

**Comment by pfez** [comment]
Mmh sorry for the noise, but I just realized that it was an actual leak in my reproducer. No need to reopen this for now. At least not due to my report.

**Comment by expnkx** [comment]
lol? leak in GCC???

**Comment by expnkx** [comment]
However, that would be a serious bug if the compiler does the wrong thing.

**Comment by pfez** [comment]
The problem in the reproducer I posted is that `CoroRet::final_suspend()` returns `std::suspend_always()`, which suspends the coroutine execution just before the end. So _technically_ the coroutine never hits the end of the execution and returns to the caller instead. So the standard does not say that the coroutine has to be destroyed. So in my reproducer there actually was a subtle leak, and Leak Sanitizer identified it correctly.

**Comment by expnkx** [comment]
> The problem in the reproducer I posted is that `CoroRet::final_suspend()` returns `std::suspend_always()`, which suspends the coroutine execution just before the end. So _technically_ the coroutine never hits the end of the execution and returns to the caller instead. So the standard does not say that the coroutine has to be destroyed. So in my reproducer there actually was a subtle leak, and Leak Sanitizer identified it correctly.

Then sanitizers should be aware of it.

**Comment by pfez** [comment]
> Then sanitizers should be aware of it.

They are, and they do the right thing!

**Comment by expnkx** [comment]
> > Then sanitizers should be aware of it.
> 
> They are, and they do the right thing!

no. I mean the sanitizers should be aware of the behavior of the never reaching the ending behavior of coroutines.

**Comment by pfez** [comment]
FWIW, we've been experimenting with coroutines and sanitizers, and until now all the times we got a report from a sanitizer it was correct. Sometimes very complicated to unravel, but in the end correct!

**Comment by pfez** [comment]
> I mean the sanitizers should be aware of the behavior of the never reaching the ending behavior of coroutines.

Not sure what you mean...

The fact that the sanitizer correctly reported the leak in my wrong reproducer means it is very well aware, and it reports correctly even subtle leaks. Am I missing something here?

If you try to change the reproducer to use `suspend_never()` instead of `suspend_always()`  the leak report correctly goes away.

Anyway, my point is the following.
The title of this issue is "Do sanitizers support C++20 Coroutines".
I have been experimenting for quite a while with both clang and gcc with coroutines and sanitizers, and until today my feeling was that, even if coroutines are experimental, the sanitizers do work properly.
Today I hit a point where I got a leak report and I really thought it was a false positive reported by the sanitizer. For this reason I posted the reproducer here, but in the end I was wrong, and the sanitizer was right!

So, in the end, from my experience, it looks like sanitizers do support C++20 coroutines. Even if coroutines are just experimental, I got great value from the sanitizers' reports with my coroutine code.

Sorry for making this thread so noisy for nothing!
