### ISSUE TITLE
False positive when overwriting with same data

### ISSUE THREAD

**Issue by qm2k** [google/sanitizers#1426]
In the framework I use a memory area is sometimes overwritten with the same data from different threads without any synchronization (the area is for interning empty strings; it contains zeroes and only zeroes are written there). Other threads may read this area. Since no data actually changes, this is all harmless, but thread sanitizer gets triggered. And I could not find any way to suppress corresponding warnings, since they are not associated with a specific function. Is it possible to either blacklist specific memory symbol, or (ideally) ignore these kind of trivial (non-changing) writes automatically?

**Comment by dvyukov** [comment]
Hi qm2k,

You can either put accesses to the range into a single function, or groups of functions with some common part in the name and then use that part in suppressions file:
https://github.com/google/sanitizers/wiki/ThreadSanitizerSuppressions

Or use `AnnotateBenignRaceSized` annotation to mark the range as racy:
https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/tsan/rtl/tsan_interface_ann.cpp#L367

ThreadSanitizer won't ignore such cases automatically because this is clearly defined by C/C++ standards as undefined behavior. This undefined behavior can well lead to arbitrary consequences in practice. See e.g. this for some examples:
https://software.intel.com/content/www/us/en/develop/blogs/benign-data-races-what-could-possibly-go-wrong.html
