### ISSUE TITLE
Inline assembly cmpxchg is not detected by TSAN

### ISSUE THREAD

**Issue by moshelevi33** [google/sanitizers#1443]
in the original implementation, when I want to lock I call this function 

```
acquire_mutex_lock(uint* lock_ptr)
{
 implement cmpxchg in inline assembly;
}

```
but TSAN does not recognize it as a lock acquire, if I instead use GCC built-in it works fine
```
acquire_mutex_lock(uint* lock_ptr)
{
 __sync_val_compare_and_swap(lock_ptr, MUTEX_FREE,MUTEX_LOCK);
}
```
 
Because I can't change the original code, is there any way to annotate TSAN?
I tried to use AnnotateRWLockAcquired but then TSAN started detecting deadlocks and a lot of problems, but this is not a waiting lock or something like that, and I had to put a lot of annotation. 
the fix with GCC build-in is straight forward but I need just a way to annotate it.
same question for another gcc atomics built in that I may implement in inline assembly(specific for now XADD)
Thanks, Moshe!

**Comment by dvyukov** [comment]
Hi @moshelevi33,

Yes, all sanitizers don't understand assembly and can have false positives and false negatives due to this.
There are several ways to fix this:
1. Define some macro for tsan build and conditionally use __sync_val_compare_and_swap (or better the new __atomic_ builtins) in tsan build.
2. Just switch the code to __atomic builtins. Compilers tend to generate fine code for them nowadays.
3. Use __tsan_acquire/release annotations: https://github.com/llvm/llvm-project/blob/533471ff2f82a5dd46ea59d5894ffe9b694c5ed9/compiler-rt/include/sanitizer/tsan_interface.h#L24-L25
4. Use tsan mutex annotations: https://github.com/llvm/llvm-project/blob/533471ff2f82a5dd46ea59d5894ffe9b694c5ed9/compiler-rt/include/sanitizer/tsan_interface.h#L76-L111 (this has an additional benefit of detecting more classes of bugs and producing better reports).
