### ISSUE TITLE
ASan breaks dead stripping (-ffunction-sections/-Wl,-gc-section on Linux, -dead_strip on OSX)

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#260]
Originally reported on Google Code with ID 260

```
Test case by Ryan Govostes:
================================================
int undefined();

int (*unused)() = undefined;

int main() {
        return 0;
}
================================================

$ clang++ t.cc -o t -Wl,--gc-sections -ffunction-sections -fsanitize=address -mllvm
-asan-globals=0
$ clang++ t.cc -o t -Wl,--gc-sections -ffunction-sections -fsanitize=address -mllvm
-asan-globals=1
/tmp/t-1710b5.o:(.data+0x0): undefined reference to `undefined()'
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)

This happens because ASan creates a per-module global array that references every global
in the module irrespective of its usage.
```

Reported by `ramosian.glider` on 2014-01-31 14:54:10

**Comment by mikea** [comment]
I stumbled on this while building fuzzers with lto. I see that vtables for classes that are never instantiated in my binary are still retained through asan tables. This e.g. keeps all icu functions in the binary even though only few are used. It's because there are c++ wrappers for most icu functionality.

**Comment by mikea** [comment]
As a data point, url_parse_fuzzer [1] under LTO with and without ASAN globals:

-rwxr-x---  1 72056 5000  18M Mar 30 13:32 url_parse_fuzzer
-rwxr-x---  1 72056 5000 5.1M Mar 30 13:28 url_parse_fuzzer.noglobals


[1] https://code.google.com/p/chromium/codesearch#chromium/src/testing/libfuzzer/fuzzers/url_parse_fuzzer.cc&sq=package:chromium&q=url_parse_fuzzer%20file:%5Esrc/&l=1

**Comment by kcc** [comment]
untested fix: 
* put the passport of a global into the global's redzone, instead of a separate global. 
* put all instrumented globals into a named section (works only for globals in unnamed section)
* register the __start_section and __stop_section instead of an array of globals
* the register callback in asan-rt will have to iterate backwards from the last element, since the redzone is in the end of a global. 
* Bonus: we can create one extra global in a section with zero size to serve as a left redzone to the first real global. 

Feel free to claim this bug if you want to start trying the above right away. 
Otherwise I'll try this eventually.

**Comment by rnk** [comment]
Apple fixed this for MachO platforms in r264645. I fixed this for COFF / Windows in r287576. Peter and I had some ideas for how to make this work for ELF, but it doesn't seem like it can be done with the existing COMDAT machinery like I did for COFF.

**Comment by morehouse** [comment]
@pcc, @rnk, @kcc, @alekseyshl:  Has anyone tried fixing this for ELF yet?

**Comment by kcc** [comment]
@eugenis did (??)

**Comment by eugenis** [comment]
Kind of did.
There are different levels of support in various linux linkers (bfd/gold/lld). It should work with lld and gold at least.

**Comment by daipipiwan12** [comment]
emm...
is this issue fixed on linux now ?
I meat same question recently...

**Comment by rnk** [comment]
Yes, ASan should be compatible with GC sections on the three major development platforms today with a modern toolchain.

**Comment by daipipiwan12** [comment]
I meet same problem when building chromium prj with clang-15.
it reported symbol undefined for some dead code,
while no such problem for no-asan build version.
may I know the patch for gc secitons with asan for clang - llvm?
