### ISSUE TITLE
tsan enhancement: support user-defined mutex names

### ISSUE THREAD

**Issue by os12** [google/sanitizers#613]
I have a home-brewed mutex wrapper that takes a user-provided name and a checker that prints the names when a predefined lock order is violated. This functionality is already implemented by TSan at run-time with no additional annotations or order specifications, which is great. However, TSan refers to the mutexes as M10, M11, etc which is, well, a little obscure. These names have nothing to do with my code and I have to look at the call stacks to figure out which lock is which.

It would be awesome to let users tag the mutexes with names. Not sure how to plumb the names through PThread calls though... Is it possible to call a special TSan function after mutex creation?

**Comment by dvyukov** [comment]
Hello Oleg,

I never seen mutexes that allow to specify names for debugging. Just checked std::mutex, pthread, boost::mutex, Qt mutex, chromium mutex, our internal mutexes; none of them allow to specify names. Do you know of any other precedents? Otherwise it looks like it will be a feature solely for you, which makes it difficult to justify the added code and memory consumption.

Also, I would expect that you need to look at stacks in either case to understand how/where it happens that mutexes are locked in different orders. Name alone is generally not enough to understand the bug.

**Comment by os12** [comment]
Hi Dmitry, it is generally possible to name a mutex, however that usecase is different. The existing API deals with OS-global named objects:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms682411%28v=vs.85%29.aspx

http://www.boost.org/doc/libs/1_57_0/doc/html/interprocess/synchronization_mechanisms.html#interprocess.synchronization_mechanisms.mutexes.mutexes_named_example

The debugging case is different. I've seen several proprietary lock order checkers are built on macros and rely on user-provided names. TSan does all of that with no manual instrumentation, but the nice, context-specific names are, of course, no more.

So, perhaps, the general question would be:
  * would the users care to manually instrument their code to get meaningful mutex names in TSan reports?

**Comment by dvyukov** [comment]
Manual post-factum annotations are definitely not possible for most _our_ use cases, because there hundreds of millions of lines of existing code (including third-party code that is generally not modified until there is a significant reason).

**Comment by kcc** [comment]
It does not look like we are going to implement it, sorry.
