### ISSUE TITLE
Dedup tool to weed out known crashes

### ISSUE THREAD

**Issue by zarana23** [google/sanitizers#684]
As per yesterday meet up with Kostya he suggested to file a issue for developing a dedup tool for ASAN.

Currently this is a blocking issue if we have to deploy fuzzer in a CI model. Dedup of crashes needs to be done to weed out known issue and file bugs for only new issues found.

**Comment by kcc** [comment]
My current idea is that we can extend the sanitizers to export 
`__sanitizer_dedup_token(char *token, size_t token_len)`
that will fill in the token with some (more-or-less) unique string based on several
top frames of the report stack trace. E.g. if the stack trace looks like
```
  #1  foo foo.c:1
  #2  bar bar.c:1
  #3  zzz zzz.c:4
  #4   rrr rrr.c:5
```
The dedup token will be `foo-bar-zzz`.
Libfuzzer will print `LIBFUZZER_DEDUP_TOKEN: foo-bar-zzz` as part of the report. 

Then deduping becomes a simple `grep` job. 

The tricky part is that the symbolizer might be absent in the asan process, 
in which case the token will be empty.

**Comment by kcc** [comment]
First attempt: http://llvm.org/viewvc/llvm-project?rev=271085&view=rev
```
     dedup_token_length
                - If positive, after printing a stack trace also print a short string
                  token based on this number of frames that will simplify
                  deduplication of the reports.
                  Example: 'DEDUP_TOKEN: foo-bar-main'. Default is 0.
```


If you set `ASAN_OPTIONS=dedup_token_length=3` env. var. you will see something like this in the reports: 

```
DEDUP_TOKEN: void Xyz::Abc<int, int>()--bar--FOO()
```

This should be sufficient to build a trivial grep-based deduplifier. 
It's not perfect. At least the following should be improved: 

* documentation
* (probably) make `dedup_token_length=3` the default, not 0
* use short function names instead of full ones, i.e. `Xyz::Abc` instead of `void Xyz::Abc<int, int>()`

**Comment by morehouse** [comment]
@kcc:  Status?

**Comment by kcc** [comment]
dedup_token_length works, no further plans.
