### ISSUE TITLE
how to solve the problem of Shadow memory range interleaves with an existing memory mapping. ASan cannot proceed correctly. ABORTING

### ISSUE THREAD

**Issue by daliands** [google/sanitizers#690]
I built addresssanitizer in aosp/5.1.1/external/compiler-rt/lib/asan,,then I found asanwrapper in /system/bin and libclang_rt.asan_arm_android.so in /system/lib.then i push libclang_rt.asan-arm-android.so in system/lib  and push app_process in /system/bin/asan。Then I run my asan test apk,it has a shadow memory problem,Sorry for the bad English.

**Comment by chefmax** [comment]
Please refer: https://github.com/google/sanitizers/wiki/AddressSanitizer#faq

Q: I'm using dynamic ASan runtime and my program crashes at start with "Shadow memory range interleaves with an existing memory mapping. ASan cannot proceed correctly.".

A1: If you are using shared ASan DSO, try LD_PRELOAD'ing Asan runtime into your program.
A2: Otherwise you are probably hitting a known limitation of dynamic runtime. Libasan is initialized at the end of program startup so if some preceeding library initializer did lots of memory allocations memory region required for ASan shadow memory could be occupied by unrelated mappings.

**Comment by yugr** [comment]
Also, have you checked
* https://source.android.com/devices/tech/debug/asan.html
* https://github.com/google/sanitizers/wiki/AddressSanitizerOnAndroid
?

**Comment by daliands** [comment]
Thank you, @chefmax I have tested LD_PRELOAD at first. but the rom can not start .i will check it later. @yugr I build the rom with make USE_CLANG_PLATFORM_BUILD:=true SANITIZE_TARGET=address -j42,but  it does not change anything .

**Comment by morehouse** [comment]
2 years old, no reproducer.  Closing.
