### ISSUE TITLE
Basic block instrumentation insufficient for code coverage collection

### ISSUE THREAD

**Issue by SimonKagstrom** [google/sanitizers#768]
I'm the author of [kcov](https://github.com/SimonKagstrom/kcov/) a code coverage collector, and I'm implementing support for the address sanitizer using `-fsanitize-coverage={bb,edge,etc}` (see [kcov issue 42](https://github.com/SimonKagstrom/kcov/issues/42)).

I've hit an issue with the instrumentation though: It seems that calls are not considered basic block terminators by the sanitizer. Consider the following example function, compiled with `-O0`:

```c
static int fn(int a)
{
	printf("fn %d\n", a);

	a = a + 1;
	a = a + 2;

	return a + 3;
}
```

(yes, silly, I know). Disassembling the output built with `-fsanitize-coverage=edge`, I get

```asm
00000000004e7d70 <fn>:
  4e7d70:	55                   	push   %rbp
  4e7d71:	48 89 e5             	mov    %rsp,%rbp
  4e7d74:	48 83 ec 10          	sub    $0x10,%rsp
  4e7d78:	31 c0                	xor    %eax,%eax
  4e7d7a:	3b 04 25 d8 8e 38 01 	cmp    0x1388ed8,%eax
  4e7d81:	89 7d f8             	mov    %edi,-0x8(%rbp)
  4e7d84:	0f 8c 16 00 00 00    	jl     4e7da0 <fn+0x30>
  4e7d8a:	48 b8 c0 8e 38 01 00 	movabs $0x1388ec0,%rax
  4e7d91:	00 00 00 
  4e7d94:	48 83 c0 18          	add    $0x18,%rax
  4e7d98:	48 89 c7             	mov    %rax,%rdi
  4e7d9b:	e8 a0 24 ff ff       	callq  4da240 <__sanitizer_cov>
  4e7da0:	48 bf 20 bd 4f 00 00 	movabs $0x4fbd20,%rdi
  4e7da7:	00 00 00 
  4e7daa:	8b 45 f8             	mov    -0x8(%rbp),%eax
  4e7dad:	89 45 fc             	mov    %eax,-0x4(%rbp)
  4e7db0:	8b 75 fc             	mov    -0x4(%rbp),%esi
  4e7db3:	b0 00                	mov    $0x0,%al
  4e7db5:	e8 06 dc f9 ff       	callq  4859c0 <__interceptor_printf>
  4e7dba:	8b 75 fc             	mov    -0x4(%rbp),%esi
  4e7dbd:	83 c6 01             	add    $0x1,%esi
  4e7dc0:	89 75 fc             	mov    %esi,-0x4(%rbp)
  4e7dc3:	8b 75 fc             	mov    -0x4(%rbp),%esi
  4e7dc6:	83 c6 02             	add    $0x2,%esi
  4e7dc9:	89 75 fc             	mov    %esi,-0x4(%rbp)
  4e7dcc:	8b 75 fc             	mov    -0x4(%rbp),%esi
  4e7dcf:	83 c6 03             	add    $0x3,%esi
  4e7dd2:	89 45 f4             	mov    %eax,-0xc(%rbp)
  4e7dd5:	89 f0                	mov    %esi,%eax
  4e7dd7:	48 83 c4 10          	add    $0x10,%rsp
  4e7ddb:	5d                   	pop    %rbp
  4e7ddc:	c3                   	retq   
  4e7ddd:	0f 1f 00             	nopl   (%rax)
```

I.e., only one call to `__sanitizer_cov` (before the printf). The lines after the printf therefore cannot be determined as executed or not, for example if the program exits or crashes in the printf. As far as I understand (from @kcc), this is not an issue with fuzzing, but it is a problem with my coverage viewer.

Using the `sancov` tool to generate a HTML report also gives the same problem as with kcov, but I don't see how it could do better anyway because of the lacking instrumentation.

**Comment by kcc** [comment]
FTR (as I mentioned elsewhere), the current implementation of `-fsanitize-coverage={bb,edge,etc}`
is likely to get deprecated in favor of http://clang.llvm.org/docs/SanitizerCoverage.html#tracing-pcs-with-guards. But it does not change the answer to your question. 

We operate on basic blocks as defined by the LLVM IR, and calls do not terminate a BB in LLVM IR. 
The simplest solution would be to split BBs after every potentially-terminating function
before the coverage instrumentation. This is relatively easy to do but I am a bit reluctant to do it
because a) I am planing quite a bit of code clean up in that module and b) the usefulness of this is not clear. (I mean, your case is understood, it's just unclear how important it is and whether it balances the extra complexity). 
@mikea is planing more analysis of coverage visualization quality, so he may return to this problem in ~ March.  

Did you also try clang instrumentation? Does it have the same issue? 
http://clang.llvm.org/docs/SourceBasedCodeCoverage.html

**Comment by SimonKagstrom** [comment]
Sorry about the later reply! I've also confused projects: My test was run with the "built-in" clang sanitizer, clang version 3.9.1.

Sorry about that as well!

**Comment by morehouse** [comment]
@kcc:  Status?

**Comment by kcc** [comment]
I guess we can close, there is nothing we want to change here. 
As for the coverage visualization, I keep recommending https://clang.llvm.org/docs/SourceBasedCodeCoverage.html
