### ISSUE TITLE
asan: SEGV reports shadow instead of user address

### ISSUE THREAD

**Issue by dvyukov** [google/sanitizers#800]
`int main() { *(volatile int*)0x123412345 = 17; }`
`==134659==ERROR: AddressSanitizer: SEGV on unknown address 0x0000a467a468`
It's better to print `0x123412345` rather than `0x0000a467a468`.

**Comment by kcc** [comment]
The address is in the shadow gap, i.e SEGV happens when we compute a shadow of a shadow-gap address (also in the shadow gap) and dereference it. 

This is extremely rare in real life since user pointers typically don't point to shadow
(unless it's uninitialized, or totally random)
And being too smart when reporting a SEGV may backfire. 
I'd prefer to not touch this part. Please reopen if you feel strongly.
