### ISSUE TITLE
ASAN misses use-after-free

### ISSUE THREAD

**Issue by zetafunction** [google/sanitizers#824]
This crashes when compiled with clang-cl.exe on Windows( without -fsanitize=address), but does not crash on Linux (with -fsanitize-address).

```c++
#include <memory>
struct DestroyedBySubclass {
  DestroyedBySubclass() : x(new int) {}

  void Destroy() {
    x.reset();
  }

  std::unique_ptr<int> x;
};

struct A {
 public:
  virtual ~A() {
    subclass_field_pointer_->Destroy();
  }
  DestroyedBySubclass* subclass_field_pointer_;
};

struct B : public A {
 public:
  B() {
    subclass_field_pointer_ = &subclass_field_;
  }

  DestroyedBySubclass subclass_field_;
};

int main() {
  B b;
}
```

**Comment by rnk** [comment]
This seems to be caused by different behavior in the two STLs. On Linux, libstdc++ nulls out the pointer member before leaving ~unique_ptr, and on Windows, it does not, so calling `reset` after ~unique_ptr causes a double free.

There isn't much asan can do, since it typically does not instrument the STL, and cannot implement use-after-destroy detection (MSan does this better).

**Comment by morehouse** [comment]
This case is better handled by MSan's use-after-dtor detection.
