### ISSUE TITLE
Sanitizer interface symbol collision?

### ISSUE THREAD

**Issue by pedronavf** [google/sanitizers#912]
I'm using gcc 6.3 and the sanitizers common interface to get information about the running sanitizers and set its options, etc. I'm using `__sanitizer_set_report_path` to set the location where I want the sanitizer output to be written to.

When I enable asan or ubsan this works fine, but when both are present (by using the `fsanitize=address,undefined` flag) only asan gets the report file file location and ubsan logs its output to stderr.

Because both `libasan` and `libubsan` link statically against `libsanitizers_common`, where `__sanitizer_set_report_path` is defined, both libraries end up with its own set of `__sanitizer_*` symbols. When linking the calling program, those symbols are taken always from the ASAN library so UBSAN never gets any setting.

I suspect this is the cause of the several reports of the `log_path` flag working in UBSAN for some people and not for others. When it doesn't work it's because both asan and ubsan are being used at the same time.

Maybe making libsanitizers_common a shared library will let several running sanitizers share the same `ReportFile` file descriptor and options? Or maybe via some macro the `__sanitizer_set_report_path` function and others could be named `__asan_set_report_path`, `__ubsan_set_report_path`, etc?

If my report is correct, I can work on a patch if given some direction on what's the best approach to take.

**Comment by kcc** [comment]
(not promising a quick fix -- we are a bit overbooked). 
Also, does this happen with clang, or only with gcc?

**Comment by pedronavf** [comment]
Thanks! As I said in my bug report, I can work on it if given some direction.

I have tested only with gcc, but I'll give clang a try and will report back.

**Comment by vitalybuka** [comment]
That's not true for clang.
-fsanitize=address,undefined will local only asan which contains some parts of ubsan.

In our make files it's RTUbsan https://github.com/llvm-project/llvm-project-20170507/blob/master/compiler-rt/lib/ubsan/CMakeLists.txt and it does not contain sanitizers_common

-fsanitize=undefined will load RTUbsan_standalone which contains sanitizers_common.

Can you use the same approach for gcc?

**Comment by chefmax** [comment]
Yes, this is a GCC specific problem.To overcome this issue you can either:
1) Use the same approach to that is implemented in Clang (UBSan embedded to ASan) in GCC. The patch will look quite trivial (e.g. https://gist.github.com/chefmax/36f9a6404d5ace62b672e1a1c8959192 we use locally in our Tizen GCC), the only difficulty here is that we need to link (unused) C++ part of UBSan even in C programs when linking static ASan runtime. This happens because GCC as opposed to Clang doesn't split C and C++ runtimes for sanitizers.
2) Just add `SANITIZER_INTERFACE_ATTRIBUTE` to `report_file` global variable. In this case all `__sanitizer_set_report_path` calls will set the same `report_file` variable. IMHO this is a hacky way to fix  the issue, it's better to use the first option if possible.

**Comment by pedronavf** [comment]
Thanks for the feedback guys! I had no problems when building with clang. I'll reach out to the gcc guys.

@chefmax I'll try your patches, thanks a lot.
