### ISSUE TITLE
SANITIZE_LITE_SERVICES in AOSP?

### ISSUE THREAD

**Issue by grbesd1** [google/sanitizers#917]
Hi Guys,

i'm trying enable ASan for all native services in AOSP.

http://androidxref.com/8.0.0_r4/xref/system/core/rootdir/Android.mk#56

i have ran below command in /system/core/. 
$ m SANITIZE_TARGET=address SANITIZE_LITE=true SANITIZE_LITE_SERVICES=true 

but build failed. i have done full build first over that i'm performing above incremental build.

Can anybody point out how to build entire native binaries with ASan.

regards,
grbesd1

**Comment by eugenis** [comment]
How did it fail?

**Comment by grbesd1** [comment]
failed in checkpublicapi-current-timestamp. 

followed by 

"you have tried to change the API from what has been previously approved."

**Comment by eugenis** [comment]
sorry, this does not tell me much.
What's your "lunch" configuration?

**Comment by eugenis** [comment]
SANITIZE_LITE_SERVICES is gone is the master branch. Try building without it (with only sanitize_target and sanitize_lite).

As for the checkpublicapi error, the suggestion is to run "m update-api" and check
for differences in the txt files in frameworks/base. It should not be caused by anything sanitizer-related.

**Comment by grbesd1** [comment]
Hi @eugenis ,

But i want to build entire native services.

http://androidxref.com/8.0.0_r4/xref/system/core/rootdir/Android.mk#56

is their a way to build sanitize on all native services.
